// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Di-nis/shortener-url/internal/handler (interfaces: URLUseCase)

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	context "context"
	reflect "reflect"

	models "github.com/Di-nis/shortener-url/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockURLUseCase is a mock of URLUseCase interface.
type MockURLUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockURLUseCaseMockRecorder
}

// MockURLUseCaseMockRecorder is the mock recorder for MockURLUseCase.
type MockURLUseCaseMockRecorder struct {
	mock *MockURLUseCase
}

// NewMockURLUseCase creates a new mock instance.
func NewMockURLUseCase(ctrl *gomock.Controller) *MockURLUseCase {
	mock := &MockURLUseCase{ctrl: ctrl}
	mock.recorder = &MockURLUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLUseCase) EXPECT() *MockURLUseCaseMockRecorder {
	return m.recorder
}

// CreateURLBatch mocks base method.
func (m *MockURLUseCase) CreateURLBatch(arg0 context.Context, arg1 []models.URL, arg2 string) ([]models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateURLBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateURLBatch indicates an expected call of CreateURLBatch.
func (mr *MockURLUseCaseMockRecorder) CreateURLBatch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateURLBatch", reflect.TypeOf((*MockURLUseCase)(nil).CreateURLBatch), arg0, arg1, arg2)
}

// CreateURLOrdinary mocks base method.
func (m *MockURLUseCase) CreateURLOrdinary(arg0 context.Context, arg1 interface{}, arg2 string) (models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateURLOrdinary", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateURLOrdinary indicates an expected call of CreateURLOrdinary.
func (mr *MockURLUseCaseMockRecorder) CreateURLOrdinary(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateURLOrdinary", reflect.TypeOf((*MockURLUseCase)(nil).CreateURLOrdinary), arg0, arg1, arg2)
}

// DeleteURLs mocks base method.
func (m *MockURLUseCase) DeleteURLs(arg0 context.Context, arg1 []models.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteURLs indicates an expected call of DeleteURLs.
func (mr *MockURLUseCaseMockRecorder) DeleteURLs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLs", reflect.TypeOf((*MockURLUseCase)(nil).DeleteURLs), arg0, arg1)
}

// GetAllURLs mocks base method.
func (m *MockURLUseCase) GetAllURLs(arg0 context.Context, arg1 string) ([]models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllURLs", arg0, arg1)
	ret0, _ := ret[0].([]models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllURLs indicates an expected call of GetAllURLs.
func (mr *MockURLUseCaseMockRecorder) GetAllURLs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllURLs", reflect.TypeOf((*MockURLUseCase)(nil).GetAllURLs), arg0, arg1)
}

// GetOriginalURL mocks base method.
func (m *MockURLUseCase) GetOriginalURL(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockURLUseCaseMockRecorder) GetOriginalURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockURLUseCase)(nil).GetOriginalURL), arg0, arg1)
}

// Ping mocks base method.
func (m *MockURLUseCase) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLUseCaseMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLUseCase)(nil).Ping), arg0)
}
