// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Di-nis/shortener-url/internal/usecase (interfaces: URLRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Di-nis/shortener-url/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockURLRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockURLRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockURLRepository)(nil).Close))
}

// Delete mocks base method.
func (m *MockURLRepository) Delete(arg0 context.Context, arg1 []models.URLBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLRepository)(nil).Delete), arg0, arg1)
}

// InsertBatch mocks base method.
func (m *MockURLRepository) InsertBatch(arg0 context.Context, arg1 []models.URLBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBatch indicates an expected call of InsertBatch.
func (mr *MockURLRepositoryMockRecorder) InsertBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBatch", reflect.TypeOf((*MockURLRepository)(nil).InsertBatch), arg0, arg1)
}

// InsertOrdinary mocks base method.
func (m *MockURLRepository) InsertOrdinary(arg0 context.Context, arg1 models.URLBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrdinary", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrdinary indicates an expected call of InsertOrdinary.
func (mr *MockURLRepositoryMockRecorder) InsertOrdinary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrdinary", reflect.TypeOf((*MockURLRepository)(nil).InsertOrdinary), arg0, arg1)
}

// Ping mocks base method.
func (m *MockURLRepository) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLRepositoryMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLRepository)(nil).Ping), arg0)
}

// SelectAll mocks base method.
func (m *MockURLRepository) SelectAll(arg0 context.Context, arg1 string) ([]models.URLBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll", arg0, arg1)
	ret0, _ := ret[0].([]models.URLBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll.
func (mr *MockURLRepositoryMockRecorder) SelectAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockURLRepository)(nil).SelectAll), arg0, arg1)
}

// SelectOriginal mocks base method.
func (m *MockURLRepository) SelectOriginal(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOriginal", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOriginal indicates an expected call of SelectOriginal.
func (mr *MockURLRepositoryMockRecorder) SelectOriginal(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOriginal", reflect.TypeOf((*MockURLRepository)(nil).SelectOriginal), arg0, arg1)
}

// SelectShort mocks base method.
func (m *MockURLRepository) SelectShort(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectShort", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectShort indicates an expected call of SelectShort.
func (mr *MockURLRepositoryMockRecorder) SelectShort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectShort", reflect.TypeOf((*MockURLRepository)(nil).SelectShort), arg0, arg1)
}
